"""ci_gate emitter — IC IR -> GitLab CI job YAML.

Emits a single CI job definition (an includable fragment, not a full
pipeline file). Each IC compiles to its own fragment so consumers can
`include:` per IC and revisions don't churn unrelated jobs.

The job runs the contract test for this IC. It triggers on:
  1. Changes to the IC source markdown (so re-emitted contract tests
     reflect spec changes).
  2. Changes to any path in IR.affected_paths (so code changes that
     violate the contract are caught).

If affected_paths is empty, only (1) fires — the gate becomes useless
for catching code-side violations. The emitter prints a warning comment
in that case so the engineer knows to populate affected_paths (or, in
v0.2+, the AE registry).

Public API: emit(ir) -> str, suggested_filename(ir) -> str
"""

from __future__ import annotations

from typing import Any

from .. import IR_SCHEMA_VERSION, PARSER_VERSION
from . import contract_test as _contract_test

EMITTER_VERSION = "0.1.0"

# Convention: under-the-consumer-repo paths (relative to repo root).
# Override at runtime via env vars in the generated CI job.
DEFAULT_TEST_DIR = "tests/contracts"
DEFAULT_IMAGE = "python:3.11"
DEFAULT_STAGE = "test"


def emit(ir: dict[str, Any]) -> str:
    """Emit a GitLab CI job YAML fragment for the given IC IR."""
    job_name = _job_name(ir)
    test_filename = _contract_test.suggested_filename(ir)
    affected_paths = ir.get("affected_paths") or []
    ic_source_relpath = _consumer_ic_path(ir)

    lines: list[str] = []
    lines.append(_header(ir, job_name))
    lines.append("")
    lines.append(f"{job_name}:")
    lines.append(f"  stage: {DEFAULT_STAGE}")
    lines.append(f"  image: ${{CONTRACT_TEST_IMAGE:-{DEFAULT_IMAGE}}}")
    lines.append("  script:")
    lines.append(
        '    - pip install --quiet -r "${CONTRACT_TEST_REQUIREMENTS:-tests/requirements.txt}"'
        " 2>/dev/null || pip install --quiet pytest"
    )
    lines.append(
        f'    - pytest -v "${{CONTRACT_TEST_DIR:-{DEFAULT_TEST_DIR}}}/{test_filename}"'
    )
    lines.append("  rules:")
    lines.append('    - if: $CI_PIPELINE_SOURCE == "merge_request_event"')
    lines.append("      changes:")
    lines.append("        # IC source — re-emitted contract test reflects spec changes")
    lines.append(f"        - {ic_source_relpath}")
    if affected_paths:
        lines.append("        # Affected implementation paths (from IR.affected_paths)")
        for path in affected_paths:
            lines.append(f"        - {path}")
    else:
        lines.append("        # WARNING: IR.affected_paths is empty — gate only fires on")
        lines.append("        # IC-source changes. Code changes that violate the contract")
        lines.append("        # will NOT trigger this job. Populate affected_paths in the")
        lines.append("        # IR (or, v0.2+, declare them via the AE registry's")
        lines.append("        # implements_globs field).")
    lines.append("  allow_failure: false")
    lines.append("")

    return "\n".join(lines) + "\n"


def suggested_filename(ir: dict[str, Any]) -> str:
    """Return the conventional filename for this IC's CI gate fragment."""
    ic_id = ir["id"].lower()
    slug = _contract_test._slug(ir.get("name", ""))
    return f"{ic_id}-{slug}.gitlab-ci.yml"


# --------------------------------------------------------------------------- #
# Internals
# --------------------------------------------------------------------------- #


def _job_name(ir: dict[str, Any]) -> str:
    """GitLab CI job name. Lowercase, dashes only — must be valid GitLab job ID."""
    ic_id = ir["id"].lower()
    slug = _contract_test._slug(ir.get("name", ""))
    return f"contract-gate-{ic_id}-{slug}"


def _consumer_ic_path(ir: dict[str, Any]) -> str:
    """Where the consumer's IC lives, relative to consumer repo root.

    The IR's source.path is the absolute path on the machine where parse
    ran. Consumers may have a different layout, so we emit the conventional
    location: dekspec/interface-contracts/<basename>.
    """
    src_path = ir.get("source", {}).get("path", "")
    basename = src_path.rsplit("/", 1)[-1] if src_path else f"{ir['id']}.md"
    return f"dekspec/interface-contracts/{basename}"


def _header(ir: dict[str, Any], job_name: str) -> str:
    src = ir.get("source", {})
    suggested = suggested_filename(ir)
    return (
        f"# GitLab CI gate for {ir['id']}: {ir.get('name', '')}\n"
        f"#\n"
        f"# Auto-generated by dekspec.constraint_compiler.emitters.ci_gate\n"
        f"# from IR schema {IR_SCHEMA_VERSION} (parser {PARSER_VERSION}, emitter {EMITTER_VERSION}).\n"
        f"#\n"
        f"# Source IC:    {src.get('path', '<unknown>')}\n"
        f"# Source SHA-256: {src.get('sha256', '<unknown>')}\n"
        f"# IC version:   {ir.get('version', '<unknown>')}\n"
        f"# IC status:    {ir.get('status', '<unknown>')}\n"
        f"# Compiled at:  {src.get('parsed_at', '<unknown>')}\n"
        f"#\n"
        f"# DO NOT EDIT MANUALLY. Re-run `dekspec compile <ic> --emit ci-gate`\n"
        f"# after the source IC changes; the file is overwritten.\n"
        f"#\n"
        f"# Include this fragment in your .gitlab-ci.yml:\n"
        f"#   include:\n"
        f"#     - local: ci/contract-gates/{suggested}\n"
        f"#\n"
        f"# Runtime overrides (set in your project's CI/CD variables):\n"
        f"#   CONTRACT_TEST_IMAGE         — container image (default: {DEFAULT_IMAGE})\n"
        f"#   CONTRACT_TEST_REQUIREMENTS  — path to requirements file (default: tests/requirements.txt)\n"
        f"#   CONTRACT_TEST_DIR           — dir containing the contract test (default: {DEFAULT_TEST_DIR})\n"
        f"#\n"
        f"# Job: {job_name}"
    )
