"""contract_test emitter — IC IR -> pytest module string.

Generates a test module per IC. All auto-generated tests are SKIPPED by
default with rich docstrings carrying the contract claim verbatim. The
engineer's job is to replace the `pytest.skip(...)` body with a real
assertion (or to dispute the claim via /write-ic --review).

Tests reference per-operation pytest fixtures the consumer must provide
in a conftest.py (e.g., `evaluate_impl` for an `evaluate` operation).
This keeps the emitter free of consumer-specific import paths.

Public API: emit(ir) -> str, suggested_filename(ir) -> str

ROADMAP — current state is intentional, not a missing feature
============================================================
Every assertion body is `pytest.skip("CONTRACT_STUB: ...")`. That is a
deliberate v0.x design choice and was flagged as such in the 2026-05-11
system audit (divergence D-39): the emitter is structurally a stub
generator today, not yet an executable contract-enforcement generator.

Planned upgrade path (no committed timeline):

  Phase 1 (today): skip-stubs with rich docstrings carrying the contract
    claim verbatim. The engineer authors real assertions in a sibling
    module that imports the fixtures.

  Phase 2 (TBD): emit type-narrowed assertion templates for the subset
    of operation shapes where the IC is fully self-describing (return
    type + invariants + error semantics all schema-typed). Skip-stubs
    remain for operations the IC describes only in prose.

  Phase 3 (TBD, possibly never): full executable contracts — runtime
    fixtures (HTTP / process / message bus) emitted from the IC's
    party kind. This crosses the consumer-isolation boundary and may
    instead become the DekFactory executor's responsibility.

Until Phase 2 lands, do not interpret a green contract-test suite as
evidence that the implementation conforms to the IC — every assertion
is `pytest.skip` and every test passes vacuously. The emitter is for
*scaffolding*; real enforcement lives in the hand-written sibling.
"""

from __future__ import annotations

import re
from typing import Any

from .. import IR_SCHEMA_VERSION, PARSER_VERSION

EMITTER_VERSION = "0.1.0"
_SLUG_NONWORD = re.compile(r"[^a-z0-9]+")


def emit(ir: dict[str, Any]) -> str:
    """Emit a pytest module string for the given IC IR.

    Output is a self-contained Python source string; the caller writes it
    to disk under whatever path the CLI / persistence layer chooses.
    """
    parts: list[str] = []
    parts.append(_module_docstring(ir))
    parts.append("")
    parts.append("from __future__ import annotations")
    parts.append("")
    parts.append("import pytest")
    parts.append("")

    operations = ir.get("interface_definition", {}).get("operations", [])
    if not operations:
        parts.append(_no_operations_block(ir))
    else:
        for op in operations:
            parts.append(_operation_section(op))

    parts.append(_error_semantics_section(ir, operations))
    parts.append(_consistency_section(ir, operations))
    parts.append(_does_not_hold_block(ir))
    parts.append(_parse_warnings_block(ir))

    return "\n".join(p for p in parts if p is not None) + "\n"


def suggested_filename(ir: dict[str, Any]) -> str:
    """Return the conventional filename for this IC's contract test module."""
    ic_id = ir["id"].lower().replace("-", "_")
    name_slug = _slug(ir.get("name", ""))
    return f"test_contract_{ic_id}_{name_slug}.py"


# --------------------------------------------------------------------------- #
# Section builders
# --------------------------------------------------------------------------- #


def _module_docstring(ir: dict[str, Any]) -> str:
    src = ir.get("source", {})
    return (
        '"""Contract tests for {id}: {name}.\n\n'
        "Auto-generated by dekspec.constraint_compiler.emitters.contract_test\n"
        "from IR schema {ir_v} (parser {parser_v}, emitter {emitter_v}).\n\n"
        "DO NOT EDIT THIS FILE MANUALLY. Re-run `dekspec compile <ic> --emit\n"
        "contract-test` after the source IC changes; the file is overwritten.\n\n"
        "Hand-written assertions belong in a sibling file (e.g.,\n"
        "test_contract_{ic_lower}_assertions.py) that imports the same\n"
        "fixtures.\n\n"
        "Source IC:    {src_path}\n"
        "Source SHA-256: {sha}\n"
        "IC version:   {ic_version}\n"
        "IC status:    {status}\n"
        "Compiled at:  {parsed_at}\n\n"
        "Engineer responsibility for each stubbed test:\n"
        "  - Replace pytest.skip(...) with the real assertion that proves\n"
        "    the contract claim named in the docstring.\n"
        "  - To dispute the claim: open /write-ic --review\n"
        '    on the source IC and amend it before re-compiling.\n"""'
    ).format(
        id=ir["id"],
        name=ir.get("name", ""),
        ir_v=IR_SCHEMA_VERSION,
        parser_v=PARSER_VERSION,
        emitter_v=EMITTER_VERSION,
        ic_lower=ir["id"].lower().replace("-", "_"),
        src_path=src.get("path", "<unknown>"),
        sha=src.get("sha256", "<unknown>"),
        ic_version=ir.get("version", "<unknown>"),
        status=ir.get("status", "<unknown>"),
        parsed_at=src.get("parsed_at", "<unknown>"),
    )


def _no_operations_block(ir: dict[str, Any]) -> str:
    return _banner("Operations") + (
        "\n\n"
        "# No operation signatures were extracted from the source IC's\n"
        "# Interface Definition section. The contract test stubs below\n"
        "# (error semantics, consistency guarantees) reference no operation\n"
        "# fixture by default; consumers must wire them up manually.\n"
        "#\n"
        "# To populate operations: tighten the IC template's Interface\n"
        "# Definition with a function-style signature line, OR hand-author\n"
        "# the IR's interface_definition.operations field.\n"
    )


def _operation_section(op: dict[str, Any]) -> str:
    name = op["name"]
    fixture = _fixture_name(name)
    sig = op.get("signature", f"{name}(...)")
    inputs = op.get("inputs") or []
    outputs = op.get("outputs") or []
    preconds = op.get("preconditions") or []

    lines = [_banner(f"Operation: {name}"), ""]
    lines.append(f"# Signature: {sig}")
    if inputs:
        lines.append("# Inputs:")
        for i in inputs:
            n = i.get("name", "?")
            t = i.get("type", "?")
            lines.append(f"#   - {n}: {t}")
    if outputs:
        lines.append("# Outputs:")
        for o in outputs:
            n = o.get("name", "?")
            t = o.get("type", "?")
            lines.append(f"#   - {n}: {t}")
    lines.append("")
    lines.append(f"def test_{name}_callable({fixture}):")
    lines.append(f'    """Smoke test: {fixture} fixture exists and is callable."""')
    lines.append(f'    assert callable({fixture}), "{fixture} must be a callable"')
    lines.append("")

    for idx, pre in enumerate(preconds):
        pre_slug = _slug(pre, max_len=40) or f"precondition_{idx}"
        test_name = f"test_{name}_precondition_{idx:02d}_{pre_slug}"
        lines.append(f"def {test_name}({fixture}):")
        lines.append('    """' + _wrap_docstring(f"Precondition: {pre}") + '"""')
        lines.append('    pytest.skip("CONTRACT_STUB: precondition assertion not yet implemented")')
        lines.append("")

    return "\n".join(lines)


def _error_semantics_section(ir: dict[str, Any], operations: list[dict[str, Any]]) -> str:
    rows = ir.get("error_semantics") or []
    if not rows:
        return ""
    fixture = _operations_fixture(operations)
    fixture_arg = f"({fixture})" if fixture else "()"

    lines = [_banner("Error semantics"), ""]
    seen: dict[str, int] = {}
    for row in rows:
        condition = row.get("condition", "(unspecified)")
        behavior = row.get("behavior")
        slug = _slug(condition, max_len=50) or "unnamed"
        if slug in seen:
            seen[slug] += 1
            slug = f"{slug}_{seen[slug]}"
        else:
            seen[slug] = 0
        test_name = f"test_error_{slug}"
        doc_lines = [f"Error condition: {condition}"]
        if "producing_party" in row:
            doc_lines.append(f"Producing party: {row['producing_party']}")
        if "detection" in row:
            doc_lines.append(f"Detection:       {row['detection']}")
        if behavior:
            doc_lines.append(f"Behavior:        {behavior}")
        else:
            doc_lines.append("Behavior:        (UNSPECIFIED in source IC — skipped permanently until filled)")
        if "consumer_responsibility" in row:
            doc_lines.append(f"Consumer resp.:  {row['consumer_responsibility']}")
        doc = "\n".join(_wrap_docstring(line) for line in doc_lines)
        lines.append(f"def {test_name}{fixture_arg}:")
        lines.append('    """' + doc + '\n    """')
        if behavior:
            lines.append(
                '    pytest.skip("CONTRACT_STUB: trigger and assertion not yet implemented")'
            )
        else:
            lines.append('    pytest.skip("CONTRACT_GAP: behavior unspecified in source IC")')
        lines.append("")
    return "\n".join(lines)


def _consistency_section(ir: dict[str, Any], operations: list[dict[str, Any]]) -> str:
    cg = ir.get("consistency_guarantees") or {}
    holds = cg.get("holds") or []
    if not holds:
        return ""
    fixture = _operations_fixture(operations)
    fixture_arg = f"({fixture})" if fixture else "()"

    lines = [_banner("Consistency guarantees — Holds"), ""]
    for idx, hold in enumerate(holds):
        slug = _slug(hold, max_len=50) or f"hold_{idx}"
        test_name = f"test_holds_{idx:02d}_{slug}"
        lines.append(f"def {test_name}{fixture_arg}:")
        lines.append('    """' + _wrap_docstring(f"Hold: {hold}") + '"""')
        lines.append('    pytest.skip("CONTRACT_STUB: assertion not yet implemented")')
        lines.append("")
    return "\n".join(lines)


def _does_not_hold_block(ir: dict[str, Any]) -> str:
    cg = ir.get("consistency_guarantees") or {}
    items = cg.get("does_not_hold") or []
    if not items:
        return ""
    lines = [_banner("Consistency guarantees — Does NOT hold (informational)"), ""]
    lines.append("# These are explicit non-guarantees. No tests are emitted; documented here")
    lines.append("# so the engineer is reminded what callers must NOT rely on.")
    for item in items:
        lines.append(f"#   - {item}")
    return "\n".join(lines)


def _parse_warnings_block(ir: dict[str, Any]) -> str:
    warnings = ir.get("parse_warnings") or []
    if not warnings:
        return ""
    lines = [_banner("Parser warnings"), ""]
    lines.append("# The parser surfaced the following gaps when extracting this IC's IR.")
    lines.append("# These do NOT block compilation but indicate template-tightening targets.")
    for w in warnings:
        lines.append(f"#   [{w['severity']}] {w['field']}: {w['reason']}")
    return "\n".join(lines)


# --------------------------------------------------------------------------- #
# Helpers
# --------------------------------------------------------------------------- #


def _banner(text: str) -> str:
    bar = "# " + "=" * 70
    return f"\n{bar}\n# {text}\n{bar}"


def _slug(text: str, max_len: int = 60) -> str:
    s = text.lower()
    s = _SLUG_NONWORD.sub("_", s)
    s = s.strip("_")
    if len(s) > max_len:
        s = s[:max_len].rstrip("_")
    return s


def _fixture_name(op_name: str) -> str:
    return f"{_slug(op_name)}_impl"


def _operations_fixture(operations: list[dict[str, Any]]) -> str:
    """Return the fixture name to inject into error/holds tests.

    For exactly-one operation contracts, use that operation's fixture so
    error/holds tests can call it directly. For multi-operation contracts
    (rare in practice), no fixture is injected — the engineer wires up
    the right one when filling the assertion.
    """
    if len(operations) == 1:
        return _fixture_name(operations[0]["name"])
    return ""


def _wrap_docstring(text: str) -> str:
    """Escape characters that would break a triple-quoted docstring."""
    return text.replace('"""', '\\"\\"\\"').replace("\n", " ")
